.TH "tmx::Vector2< T >" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::Vector2< T > \- Two dimensional vector used to store points and positions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Types\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVector2\fP (T x, T y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBx\fP"
.br
.ti -1c
.RI "T \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
struct tmx::Vector2< T >"
Two dimensional vector used to store points and positions\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
