.TH "tmx::TileLayer" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::TileLayer \- A layer made up from a series of tile sets\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TileLayer\&.hpp>\fP
.PP
Inherits \fBtmx::Layer\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTile\fP"
.br
.RI "\fBTile\fP information for a layer\&. "
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFlipFlag\fP { \fBHorizontal\fP = 0x8, \fBVertical\fP = 0x4, \fBDiagonal\fP = 0x2 }
.RI "Flags used to tell if a tile is flipped when drawn\&. ""
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTileLayer\fP (std::size_t)"
.br
.ti -1c
.RI "Type \fBgetType\fP () const override"
.br
.RI "Returns a Type value representing the concrete type\&. Use this when deciding which conrete layer type to use when calling the templated function \fBgetLayerAs<T>()\fP "
.ti -1c
.RI "void \fBparse\fP (const pugi::xml_node &) override"
.br
.RI "Attempts to parse the specific node layer type\&. "
.ti -1c
.RI "const std::vector< \fBTile\fP > & \fBgetTiles\fP () const"
.br
.RI "Returns the list of tiles used to make up the layer\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A layer made up from a series of tile sets\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
