.TH "tmx::TileLayer::Tile" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::TileLayer::Tile \- \fBTile\fP information for a layer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TileLayer\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint32_t \fBID\fP = 0"
.br
.RI "Global ID of the tile\&. "
.ti -1c
.RI "std::uint8_t \fBflipFlags\fP = 0"
.br
.RI "Flags marking if the tile should be flipped when drawn\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBTile\fP information for a layer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
