.TH "tmx::ObjectGroup" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::ObjectGroup \- \fBObjectGroup\fP layers contain a series of Objects which may be made up of shapes or images\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ObjectGroup\&.hpp>\fP
.PP
Inherits \fBtmx::Layer\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDrawOrder\fP { \fBIndex\fP, \fBTopDown\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Type \fBgetType\fP () const override"
.br
.RI "Returns a Type value representing the concrete type\&. Use this when deciding which conrete layer type to use when calling the templated function \fBgetLayerAs<T>()\fP "
.ti -1c
.RI "void \fBparse\fP (const pugi::xml_node &) override"
.br
.RI "Attempts to parse the specific node layer type\&. "
.ti -1c
.RI "const \fBColour\fP & \fBgetColour\fP () const"
.br
.RI "Returns the colour associated with this layer\&. "
.ti -1c
.RI "DrawOrder \fBgetDrawOrder\fP () const"
.br
.RI "Returns the DrawOrder for the objects in this group\&. Defaults to TopDown, where Objects are drawn sorted by Y position\&. "
.ti -1c
.RI "const std::vector< \fBProperty\fP > & \fBgetProperties\fP () const"
.br
.RI "Returns a reference to the vector of properties for the \fBObjectGroup\fP\&. "
.ti -1c
.RI "const std::vector< \fBObject\fP > & \fBgetObjects\fP () const"
.br
.RI "Returns a reference to the vector of Objects which belong to the group\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBObjectGroup\fP layers contain a series of Objects which may be made up of shapes or images\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
