.TH "tmx::Tileset::Tile::Animation::Frame" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::Tileset::Tile::Animation::Frame \- A frame within an animation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tileset\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint32_t \fBtileID\fP = 0"
.br
.ti -1c
.RI "std::uint32_t \fBduration\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
A frame within an animation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
