.TH "tmx::Version" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::Version \- Holds the xml version of the loaded map\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVersion\fP (std::uint16_t maj=0, std::uint16_t min=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint16_t \fBupper\fP"
.br
.ti -1c
.RI "std::uint16_t \fBlower\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds the xml version of the loaded map\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
