.TH "tmx::Colour" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::Colour \- Contains the red, green, blue and alpha values of a colour in the range 0 - 255\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Types\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColour\fP (std::uint8_t red=0, std::uint8_t green=0, std::uint8_t blue=0, std::uint8_t alpha=255)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint8_t \fBr\fP"
.br
.ti -1c
.RI "std::uint8_t \fBg\fP"
.br
.ti -1c
.RI "std::uint8_t \fBb\fP"
.br
.ti -1c
.RI "std::uint8_t \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the red, green, blue and alpha values of a colour in the range 0 - 255\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
