.TH "tmx::Text" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::Text \- Contains the text information stored in a \fBText\fP object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Object\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBHAlign\fP { \fBLeft\fP, \fBCentre\fP, \fBRight\fP }"
.br
.ti -1c
.RI "enum \fBVAlign\fP { \fBTop\fP, \fBCentre\fP, \fBBottom\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfontFamily\fP"
.br
.ti -1c
.RI "std::uint32_t \fBpixelSize\fP = 16"
.br
.RI "pixels, not points "
.ti -1c
.RI "bool \fBwrap\fP = false"
.br
.ti -1c
.RI "\fBColour\fP \fBcolour\fP"
.br
.ti -1c
.RI "bool \fBbold\fP = false"
.br
.ti -1c
.RI "bool \fBitalic\fP = false"
.br
.ti -1c
.RI "bool \fBunderline\fP = false"
.br
.ti -1c
.RI "bool \fBstrikethough\fP = false"
.br
.ti -1c
.RI "bool \fBkerning\fP = true"
.br
.ti -1c
.RI "enum tmx::Text::HAlign \fBhAlign\fP = HAlign::Left"
.br
.ti -1c
.RI "enum tmx::Text::VAlign \fBvAlign\fP = VAlign::Top"
.br
.ti -1c
.RI "std::string \fBcontent\fP"
.br
.RI "actual string content "
.in -1c
.SH "Detailed Description"
.PP 
Contains the text information stored in a \fBText\fP object\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
