.TH "tmx::Tileset::Tile::Animation" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::Tileset::Tile::Animation \- a group of frames which make up an animation  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tileset\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFrame\fP"
.br
.RI "A frame within an animation\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBFrame\fP > \fBframes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
a group of frames which make up an animation 

.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
