.TH "tmx::Rectangle< T >" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::Rectangle< T > \- Describes a rectangular area, such as an AABB (axis aligned bounding box)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Types\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRectangle\fP (T l, T t, T w, T h)"
.br
.ti -1c
.RI "\fBRectangle\fP (\fBVector2\fP< T > position, \fBVector2\fP< T > size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBleft\fP"
.br
.ti -1c
.RI "T \fBtop\fP"
.br
.ti -1c
.RI "T \fBwidth\fP"
.br
.ti -1c
.RI "T \fBheight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
struct tmx::Rectangle< T >"
Describes a rectangular area, such as an AABB (axis aligned bounding box) 

.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
