.TH "tmx::LayerGroup" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::LayerGroup \- \fBLayer\fP groups are used to organize the layers of the map in a hierarchy\&. They can contain all other layer types including more layer groups to further nest layers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LayerGroup\&.hpp>\fP
.PP
Inherits \fBtmx::Layer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayerGroup\fP (const std::string &workDir, const \fBVector2u\fP &tileCount)"
.br
.ti -1c
.RI "\fBLayerGroup\fP (const \fBLayerGroup\fP &)=delete"
.br
.ti -1c
.RI "const \fBLayerGroup\fP & \fBoperator=\fP (const \fBLayerGroup\fP &)=delete"
.br
.ti -1c
.RI "\fBLayerGroup\fP (\fBLayerGroup\fP &&)=default"
.br
.ti -1c
.RI "\fBLayerGroup\fP & \fBoperator=\fP (\fBLayerGroup\fP &&)=default"
.br
.ti -1c
.RI "Type \fBgetType\fP () const override"
.br
.RI "Returns a Type value representing the concrete type\&. Use this when deciding which conrete layer type to use when calling the templated function \fBgetLayerAs<T>()\fP "
.ti -1c
.RI "void \fBparse\fP (const pugi::xml_node &) override"
.br
.RI "Attempts to parse the specific node layer type\&. "
.ti -1c
.RI "const std::vector< Layer::Ptr > & \fBgetLayers\fP () const"
.br
.RI "Returns a reference to the vector containing the layer data\&. Layers are pointer-to-baseclass, the concrete type of which can be found via \fBLayer::getType()\fP "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBLayer\fP groups are used to organize the layers of the map in a hierarchy\&. They can contain all other layer types including more layer groups to further nest layers\&. 
.SH "Member Function Documentation"
.PP 
.SS "const std::vector<Layer::Ptr>& tmx::LayerGroup::getLayers () const\fC [inline]\fP"

.PP
Returns a reference to the vector containing the layer data\&. Layers are pointer-to-baseclass, the concrete type of which can be found via \fBLayer::getType()\fP 
.PP
\fBSee also:\fP
.RS 4
\fBLayer\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
