.TH "tmx::Tileset::Terrain" 3 "Tue Dec 31 2019" "Version 1.0.0" "tmxlite" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tmx::Tileset::Terrain \- \fBTerrain\fP information with which one or more tiles may be associated\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tileset\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "std::uint32_t \fBtileID\fP = \-1"
.br
.ti -1c
.RI "std::vector< \fBProperty\fP > \fBproperties\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTerrain\fP information with which one or more tiles may be associated\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for tmxlite from the source code\&.
